// Central TypeScript types for Guest.
// Learn: a type is a promise about shape. Instead of re-declaring the
// Guest shape inside every file, we declare it ONCE here and import it
// wherever needed. If the shape changes tomorrow, you change one file.

// Attendance answer. 'pending' = invited but no reply yet.
export type AttendanceStatus = "pending" | "yes" | "no";

export interface Guest {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null;
  attendance_status: AttendanceStatus;
  ticket_number: string | null;
  qr_token: string | null;
  is_sent: number;
  // NULL until accredited (one-day event: a guest is accredited at most once).
  accredited_at: string | null;
  created_at: string;
  updated_at: string;
}

// Shape of the POST /api/guests request body.
// Kept separate from CreateGuestInput because HTTP input is untrusted:
// fields arrive as unknown and the service validates before use.
export interface RegisterGuestBody {
  first_name?: unknown;
  last_name?: unknown;
  email?: unknown;
  phone?: unknown;
}

// Shape of the PATCH /api/guests/:id request body.
// Every field is optional and untrusted (unknown); the service validates.
export interface UpdateGuestBody {
  first_name?: unknown;
  last_name?: unknown;
  email?: unknown;
  phone?: unknown;
  attendance_status?: unknown;
}

// Validated patch: only updatable fields, already normalized.
// System fields (id, ticket_number, qr_token, is_sent, timestamps)
// can never appear here - the service rejects them with a 400.
export interface UpdateGuestInput {
  first_name?: string;
  last_name?: string;
  email?: string;
  phone?: string | null;
  attendance_status?: AttendanceStatus;
}

// Input allowed when creating a guest.
// id / timestamps are generated by the database, so they are omitted.
export interface CreateGuestInput {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string | null;
  attendance_status?: AttendanceStatus;
  ticket_number?: string | null;
  qr_token?: string | null;
}
